### PR TITLE
Detection of hooks in Import Address Table

### PR DESCRIPTION
**Pull request by xalicex**
Hello,

This code detects hooks in the Import Address Table and replace the hooks with the true address of the functions.

I thought it could be usefull in this repo :)

### CODE REVIEW

**Comment by Mr-Un1k0d3r** [comment]
Thanks for contribution ❤

**Comment by xalicex** [comment]
You're welcome !

**Comment by Mr-Un1k0d3r** [comment]
Would you mind adding information about it in the readme.

**Comment by xalicex** [comment]
No problem ! It's done !

**Pull request merged**
